// WIP / DEFERRED — data-only battle-command tables. The data transcription
// below is byte-correct (all 23 tables: catch/damage/pickup/prize tables, the
// 4 TempStatsStruct stat-order tables, 2 ManagedSpriteTemplates, and the
// 225-entry sBattleScriptCommandTable). It is NOT linked: main.lsf stays on
// asm/overlay_12_battle_command.o so the ROM matches.
//
// BLOCKER (rodata size-sort): MWCC `-ipa file` emits each `const` global as a
// SEPARATE .rodata section and the linker concatenates them SIZE-sorted, but
// retail lays them out in SOURCE order (e.g. the 9/10/13-byte pickup-weight /
// honey-gather / camouflage tables sit AFTER the 900-byte command table, not
// at the front). Confirmed via `nm main.elf`: sFlailDamageTable links at
// 0x0226C318 instead of retail 0x0226C300, etc. — see [[static-const-tables-
// must-be-one-array-not-separate-objects]].
//
// TO FINISH (planned consolidation pass): wrap ALL tables as members of ONE
// `static const struct { ... }` (one section -> source order preserved, with
// padding members to reproduce the inter-table .balign 4), expose the 20 public
// names via `#define sX (sRodata.fX)` in a new shared header, and replace the
// local `extern` decls in battle_command.c + ~10 other consumers (battle_*.c)
// with that header. ov12_0226C324 is a local (non-.public) table — keep it in
// the struct so it isn't DCE'd. Then flip main.lsf:631 asm->src and compare.

#include "global.h"

#include "constants/battle.h"
#include "constants/items.h"
#include "constants/moves.h"
#include "constants/pokemon.h"
#include "constants/species.h"
#include "constants/trainer_class.h"

#include "battle/battle_command.h"

#include "sprite_system.h"

typedef struct TempStatsStruct {
    u32 stats[6];
} TempStatsStruct;

const u8 sStandardBallCatchRates[4] = { 20, 15, 10, 15 };

const u8 sTrumpCardPowerTable[] = { 200, 80, 60, 50, 40 };

const u16 sProtectSuccessChance[4] = { 0xFFFF, 0x7FFF, 0x3FFF, 0x1FFF };

const u8 sFlailDamageTable[6][2] = {
    { 1,  200 },
    { 5,  150 },
    { 12, 100 },
    { 21, 80  },
    { 42, 40  },
    { 64, 20  },
};

const u16 sPickupTable2[11] = {
    ITEM_HYPER_POTION,
    ITEM_NUGGET,
    ITEM_KINGS_ROCK,
    ITEM_FULL_RESTORE,
    ITEM_ETHER,
    ITEM_IRON_BALL,
    ITEM_TM56,
    ITEM_ELIXIR,
    ITEM_TM86,
    ITEM_LEFTOVERS,
    ITEM_TM26,
};

const u32 ov12_0226C324[6] = {
    NUM_BATTLE_STATS,
    STAT_ATK,
    STAT_DEF,
    STAT_SPATK,
    STAT_SPDEF,
    STAT_SPEED,
};

const TempStatsStruct ov12_0226C33C = {
    { MON_DATA_MAX_HP, MON_DATA_ATK, MON_DATA_DEF, MON_DATA_SP_ATK, MON_DATA_SP_DEF, MON_DATA_SPEED }
};

const TempStatsStruct ov12_0226C354 = {
    { MON_DATA_MAX_HP, MON_DATA_ATK, MON_DATA_DEF, MON_DATA_SP_ATK, MON_DATA_SP_DEF, MON_DATA_SPEED }
};

const TempStatsStruct ov12_0226C36C = {
    { NUM_BATTLE_STATS, STAT_ATK, STAT_DEF, STAT_SPATK, STAT_SPDEF, STAT_SPEED }
};

const TempStatsStruct ov12_0226C384 = {
    { MON_DATA_MAX_HP, MON_DATA_ATK, MON_DATA_DEF, MON_DATA_SP_ATK, MON_DATA_SP_DEF, MON_DATA_SPEED }
};

const u16 sLowKickDamageTable[6][2] = {
    { 100,    20     },
    { 250,    40     },
    { 500,    60     },
    { 1000,   80     },
    { 2000,   100    },
    { 0xFFFF, 0xFFFF },
};

const u16 sNaturePowerMoveTable[] = {
    MOVE_EARTHQUAKE,
    MOVE_EARTHQUAKE,
    MOVE_SEED_BOMB,
    MOVE_SEED_BOMB,
    MOVE_ROCK_SLIDE,
    MOVE_ROCK_SLIDE,
    MOVE_BLIZZARD,
    MOVE_HYDRO_PUMP,
    MOVE_ICE_BEAM,
    MOVE_TRI_ATTACK,
    MOVE_MUD_BOMB,
    MOVE_AIR_SLASH,
    MOVE_TRI_ATTACK,
};

const u8 sSafariCatchRateStages[13][2] = {
    { 10, 40 },
    { 10, 35 },
    { 10, 30 },
    { 10, 25 },
    { 10, 20 },
    { 10, 15 },
    { 10, 10 },
    { 15, 10 },
    { 20, 10 },
    { 25, 10 },
    { 30, 10 },
    { 35, 10 },
    { 40, 10 },
};

const u16 sMoonBallPokemon[14] = {
    SPECIES_NIDORAN_F,
    SPECIES_NIDORINA,
    SPECIES_NIDOQUEEN,
    SPECIES_NIDORAN_M,
    SPECIES_NIDORINO,
    SPECIES_NIDOKING,
    SPECIES_CLEFFA,
    SPECIES_CLEFAIRY,
    SPECIES_CLEFABLE,
    SPECIES_IGGLYBUFF,
    SPECIES_JIGGLYPUFF,
    SPECIES_WIGGLYTUFF,
    SPECIES_SKITTY,
    SPECIES_DELCATTY,
};

const u16 sPickupTable1[18] = {
    ITEM_POTION,
    ITEM_ANTIDOTE,
    ITEM_SUPER_POTION,
    ITEM_GREAT_BALL,
    ITEM_REPEL,
    ITEM_ESCAPE_ROPE,
    ITEM_FULL_HEAL,
    ITEM_HYPER_POTION,
    ITEM_ULTRA_BALL,
    ITEM_REVIVE,
    ITEM_RARE_CANDY,
    ITEM_SUN_STONE,
    ITEM_MOON_STONE,
    ITEM_HEART_SCALE,
    ITEM_FULL_RESTORE,
    ITEM_MAX_REVIVE,
    ITEM_PP_UP,
    ITEM_MAX_ELIXIR,
};

const ManagedSpriteTemplate sLevelUpNameplateTemplate = {
    0x80,
    0x00,
    0x00,
    0,
    200,
    0,
    NNS_G2D_VRAM_TYPE_2DMAIN,
    { 20021, 20016, 20013, 20013, -1, -1 },
    1,
    0,
};

const ManagedSpriteTemplate sPokeIconTemplate = {
    0x98,
    0x18,
    0x00,
    0,
    100,
    0,
    NNS_G2D_VRAM_TYPE_2DMAIN,
    { 20022, 20017, 20014, 20014, -1, -1 },
    1,
    0,
};

const u32 sSecretPowerEffectTable[] = {
    0x8000001B,
    0x8000001B,
    0x80000001,
    0x80000001,
    0x80000008,
    0x80000008,
    0x80000004,
    0x80000016,
    0x80000004,
    0x80000005,
    0x80000018,
    0x8000001C,
    0x80000005,
};

const u16 sPrizeMoneyTbl[0x81][2] = {
    { TRAINERCLASS_PKMN_TRAINER_ETHAN,     0  },
    { TRAINERCLASS_PKMN_TRAINER_LYRA,      0  },
    { TRAINERCLASS_YOUNGSTER,              4  },
    { TRAINERCLASS_LASS,                   4  },
    { TRAINERCLASS_CAMPER,                 4  },
    { TRAINERCLASS_PICNICKER,              4  },
    { TRAINERCLASS_BUG_CATCHER,            4  },
    { TRAINERCLASS_AROMA_LADY,             8  },
    { TRAINERCLASS_TWINS,                  4  },
    { TRAINERCLASS_HIKER,                  8  },
    { TRAINERCLASS_BATTLE_GIRL,            4  },
    { TRAINERCLASS_FISHERMAN,              8  },
    { TRAINERCLASS_CYCLIST_M,              8  },
    { TRAINERCLASS_CYCLIST_F,              8  },
    { TRAINERCLASS_BLACK_BELT,             6  },
    { TRAINERCLASS_ARTIST,                 12 },
    { TRAINERCLASS_PKMN_BREEDER_M,         12 },
    { TRAINERCLASS_PKMN_BREEDER_F,         12 },
    { TRAINERCLASS_COWGIRL,                4  },
    { TRAINERCLASS_JOGGER,                 8  },
    { TRAINERCLASS_POKEFAN_M,              16 },
    { TRAINERCLASS_POKEFAN,                16 },
    { TRAINERCLASS_POKE_KID,               2  },
    { TRAINERCLASS_RIVAL,                  16 },
    { TRAINERCLASS_ACE_TRAINER_M,          15 },
    { TRAINERCLASS_ACE_TRAINER_F,          15 },
    { TRAINERCLASS_WAITRESS,               8  },
    { TRAINERCLASS_VETERAN,                20 },
    { TRAINERCLASS_NINJA_BOY,              2  },
    { TRAINERCLASS_DRAGON_TAMER,           8  },
    { TRAINERCLASS_BIRD_KEEPER_GS,         8  },
    { TRAINERCLASS_JUGGLER,                8  },
    { TRAINERCLASS_RICH_BOY,               40 },
    { TRAINERCLASS_LADY,                   40 },
    { TRAINERCLASS_GENTLEMAN,              50 },
    { TRAINERCLASS_SOCIALITE,              50 },
    { TRAINERCLASS_BEAUTY,                 14 },
    { TRAINERCLASS_COLLECTOR,              16 },
    { TRAINERCLASS_POLICEMAN,              10 },
    { TRAINERCLASS_PKMN_RANGER_M,          15 },
    { TRAINERCLASS_PKMN_RANGER_F,          15 },
    { TRAINERCLASS_SCIENTIST,              12 },
    { TRAINERCLASS_SWIMMER_M,              4  },
    { TRAINERCLASS_SWIMMER_F,              4  },
    { TRAINERCLASS_TUBER_M,                1  },
    { TRAINERCLASS_TUBER_F,                1  },
    { TRAINERCLASS_SAILOR,                 8  },
    { TRAINERCLASS_KIMONO_GIRL,            30 },
    { TRAINERCLASS_RUIN_MANIAC,            12 },
    { TRAINERCLASS_PSYCHIC_M,              8  },
    { TRAINERCLASS_PSYCHIC_F,              8  },
    { TRAINERCLASS_PI,                     30 },
    { TRAINERCLASS_GUITARIST,              6  },
    { TRAINERCLASS_ACE_TRAINER_M_GS,       15 },
    { TRAINERCLASS_ACE_TRAINER_F_GS,       15 },
    { TRAINERCLASS_TEAM_ROCKET,            10 },
    { TRAINERCLASS_SKIER,                  8  },
    { TRAINERCLASS_ROUGHNECK,              6  },
    { TRAINERCLASS_CLOWN,                  6  },
    { TRAINERCLASS_WORKER,                 10 },
    { TRAINERCLASS_SCHOOL_KID_M,           5  },
    { TRAINERCLASS_SCHOOL_KID_F,           5  },
    { TRAINERCLASS_TEAM_ROCKET_F,          10 },
    { TRAINERCLASS_BURGLAR,                4  },
    { TRAINERCLASS_FIREBREATHER,           8  },
    { TRAINERCLASS_BIKER,                  4  },
    { TRAINERCLASS_LEADER_FALKNER,         30 },
    { TRAINERCLASS_LEADER_BUGSY,           30 },
    { TRAINERCLASS_POKE_MANIAC,            16 },
    { TRAINERCLASS_LEADER_WHITNEY,         30 },
    { TRAINERCLASS_LEADER_MORTY,           30 },
    { TRAINERCLASS_RANCHER,                10 },
    { TRAINERCLASS_LEADER_PRYCE,           30 },
    { TRAINERCLASS_LEADER_JASMINE,         30 },
    { TRAINERCLASS_LEADER_CHUCK,           30 },
    { TRAINERCLASS_LEADER_CLAIR,           30 },
    { TRAINERCLASS_TEACHER,                12 },
    { TRAINERCLASS_SUPER_NERD,             12 },
    { TRAINERCLASS_SAGE,                   12 },
    { TRAINERCLASS_MEDIUM,                 12 },
    { TRAINERCLASS_PARASOL_LADY,           8  },
    { TRAINERCLASS_WAITER,                 8  },
    { TRAINERCLASS_CHAMPION,               50 },
    { TRAINERCLASS_CAMERAMAN,              8  },
    { TRAINERCLASS_REPORTER,               10 },
    { TRAINERCLASS_IDOL,                   18 },
    { TRAINERCLASS_ELITE_FOUR_WILL,        30 },
    { TRAINERCLASS_ELITE_FOUR_KAREN,       30 },
    { TRAINERCLASS_ELITE_FOUR_KOGA,        30 },
    { TRAINERCLASS_LEADER_BROCK,           30 },
    { TRAINERCLASS_PKMN_TRAINER_CHERYL,    30 },
    { TRAINERCLASS_PKMN_TRAINER_RILEY,     30 },
    { TRAINERCLASS_PKMN_TRAINER_BUCK,      30 },
    { TRAINERCLASS_PKMN_TRAINER_MIRA,      30 },
    { TRAINERCLASS_PKMN_TRAINER_MARLEY,    30 },
    { TRAINERCLASS_PKMN_TRAINER_FTR_LUCAS, 25 },
    { TRAINERCLASS_PKMN_TRAINER_FTR_DAWN,  25 },
    { TRAINERCLASS_TOWER_TYCOON,           0  },
    { TRAINERCLASS_LEADER_MISTY,           30 },
    { TRAINERCLASS_HALL_MATRON,            0  },
    { TRAINERCLASS_FACTORY_HEAD,           0  },
    { TRAINERCLASS_ARCADE_STAR,            0  },
    { TRAINERCLASS_CASTLE_VALET,           0  },
    { TRAINERCLASS_LEADER_LT_SURGE,        30 },
    { TRAINERCLASS_LEADER_ERIKA,           30 },
    { TRAINERCLASS_LEADER_JANINE,          30 },
    { TRAINERCLASS_LEADER_SABRINA,         30 },
    { TRAINERCLASS_LEADER_BLAINE,          30 },
    { TRAINERCLASS_PKMN_TRAINER_RED,       50 },
    { TRAINERCLASS_LEADER_BLUE,            40 },
    { TRAINERCLASS_ELDER,                  30 },
    { TRAINERCLASS_ELITE_FOUR_BRUNO,       30 },
    { TRAINERCLASS_SCIENTIST_GS,           8  },
    { TRAINERCLASS_EXECUTIVE_ARIANA,       20 },
    { TRAINERCLASS_BOARDER,                8  },
    { TRAINERCLASS_EXECUTIVE_ARCHER,       20 },
    { TRAINERCLASS_EXECUTIVE_PROTON,       10 },
    { TRAINERCLASS_EXECUTIVE_PETREL,       10 },
    { TRAINERCLASS_PASSERBY,               25 },
    { TRAINERCLASS_MYSTERY_MAN,            30 },
    { TRAINERCLASS_DOUBLE_TEAM,            30 },
    { TRAINERCLASS_YOUNG_COUPLE,           16 },
    { TRAINERCLASS_PKMN_TRAINER_LANCE,     0  },
    { TRAINERCLASS_ROCKET_BOSS,            45 },
    { TRAINERCLASS_PKMN_TRAINER_LUCAS_DP,  0  },
    { TRAINERCLASS_PKMN_TRAINER_DAWN_DP,   0  },
    { TRAINERCLASS_PKMN_TRAINER_LUCAS_PT,  0  },
    { TRAINERCLASS_PKMN_TRAINER_DAWN_PT,   0  },
    { TRAINERCLASS_BIRD_KEEPER,            8  },
};

const BtlCmdFunc sBattleScriptCommandTable[] = {
    BtlCmd_PlayEncounterAnimation,
    BtlCmd_SetPokemonEncounter,
    BtlCmd_PokemonSlideIn,
    BtlCmd_PokemonSendOut,
    BtlCmd_RecallPokemon,
    BtlCmd_DeletePokemon,
    BtlCmd_SetTrainerEncounter,
    BtlCmd_ThrowPokeball,
    BtlCmd_TrainerSlideOut,
    BtlCmd_TrainerSlideIn,
    BtlCmd_BackgroundSlideIn,
    BtlCmd_HealthbarSlideIn,
    BtlCmd_HealthbarSlideInDelay,
    BtlCmd_HealthbarSlideOut,
    BtlCmd_Wait,
    BtlCmd_CalcDamage,
    BtlCmd_CalcDamageRaw,
    BtlCmd_PrintAttackMessage,
    BtlCmd_PrintMessage,
    BtlCmd_PrintGlobalMessage,
    BtlCmd_PrintBufferedMessage,
    BtlCmd_BufferMessage,
    BtlCmd_BufferLocalMessage,
    BtlCmd_PlayMoveAnimation,
    BtlCmd_PlayMoveAnimationOnMons,
    BtlCmd_FlickerMon,
    BtlCmd_UpdateHealthbarValue,
    BtlCmd_UpdateHealthbar,
    BtlCmd_TryFaintMon,
    BtlCmd_PlayFaintAnimation,
    BtlCmd_WaitButtonABTime,
    BtlCmd_PlaySound,
    BtlCmd_CompareVarToValue,
    BtlCmd_CompareMonDataToValue,
    BtlCmd_FadeOutBattle,
    BtlCmd_GoToSubscript,
    BtlCmd_GoToEffectScript,
    BtlCmd_GoToMoveScript,
    BtlCmd_CalcCrit,
    BtlCmd_CalcExpGain,
    BtlCmd_StartGetExpTask,
    BtlCmd_WaitGetExpTask,
    BtlCmd_WaitGetExpTaskLoop,
    BtlCmd_ShowParty,
    BtlCmd_WaitMonSelection,
    BtlCmd_SwitchAndUpdateMon,
    BtlCmd_GoToIfAnySwitches,
    BtlCmd_StartCatchMonTask,
    BtlCmd_WaitCatchMonTask,
    BtlCmd_SetMultiHit,
    BtlCmd_UpdateVar,
    BtlCmd_ChangeStatStage,
    BtlCmd_UpdateMonData,
    BtlCmd_ClearVolatileStatus,
    BtlCmd_ToggleVanish,
    BtlCmd_CheckAbility,
    BtlCmd_Random,
    BtlCmd_UpdateVar2,
    BtlCmd_UpdateMonDataFromVar,
    BtlCmd_Goto,
    BtlCmd_Call,
    BtlCmd_CallFromVar,
    BtlCmd_SetMirrorMove,
    BtlCmd_ResetAllStatChanges,
    BtlCmd_LockMoveChoice,
    BtlCmd_UnlockMoveChoice,
    BtlCmd_SetHealthbarStatus,
    BtlCmd_PrintTrainerMessage,
    BtlCmd_PayPrizeMoney,
    BtlCmd_PlayBattleAnimation,
    BtlCmd_PlayBattleAnimationOnMons,
    BtlCmd_PlayBattleAnimationFromVar,
    BtlCmd_PrintRecallMessage,
    BtlCmd_PrintSendOutMessage,
    BtlCmd_PrintEncounterMessage,
    BtlCmd_PrintFirstSendOutMessage,
    BtlCmd_PrintBufferedTrainerMessage,
    BtlCmd_TryConversion,
    BtlCmd_CompareVarToVar,
    BtlCmd_CompareMonDataToVar,
    BtlCmd_AddPayDayMoney,
    BtlCmd_TryLightScreen,
    BtlCmd_TryReflect,
    BtlCmd_TryMist,
    BtlCmd_TryOHKOMove,
    BtlCmd_DivideVarByValue,
    BtlCmd_DivideVarByVar,
    BtlCmd_TryMimic,
    BtlCmd_Metronome,
    BtlCmd_TryDisable,
    BtlCmd_Counter,
    BtlCmd_MirrorCoat,
    BtlCmd_TryEncore,
    BtlCmd_TryConversion2,
    BtlCmd_TrySketch,
    BtlCmd_TrySleepTalk,
    BtlCmd_CalcFlailPower,
    BtlCmd_TrySpite,
    BtlCmd_TryPartyStatusRefresh,
    BtlCmd_TryStealItem,
    BtlCmd_TryProtection,
    BtlCmd_TrySubstitute,
    BtlCmd_TryWhirlwind,
    BtlCmd_Transform,
    BtlCmd_TrySpikes,
    BtlCmd_CheckSpikes,
    BtlCmd_TryPerishSong,
    BtlCmd_GetTurnOrderBySpeed,
    BtlCmd_GoToIfValidMon,
    BtlCmd_EndOfTurnWeatherEffect,
    BtlCmd_CalcRolloutPower,
    BtlCmd_CalcFuryCutterPower,
    BtlCmd_TryAttract,
    BtlCmd_TrySafeguard,
    BtlCmd_Present,
    BtlCmd_CalcMagnitudePower,
    BtlCmd_TryReplaceFaintedMon,
    BtlCmd_RapidSpin,
    BtlCmd_WeatherHPRecovery,
    BtlCmd_CalcHiddenPowerParams,
    BtlCmd_CopyStatStages,
    BtlCmd_TryFutureSight,
    BtlCmd_CheckMoveHit,
    BtlCmd_TryTeleport,
    BtlCmd_BeatUp,
    BtlCmd_FollowMe,
    BtlCmd_TryHelpingHand,
    BtlCmd_TrySwapItems,
    BtlCmd_TryWish,
    BtlCmd_TryAssist,
    BtlCmd_TrySetMagicCoat,
    BtlCmd_MagicCoat,
    BtlCmd_CalcRevengeDamageMul,
    BtlCmd_TryBreakScreens,
    BtlCmd_TryYawn,
    BtlCmd_TryKnockOff,
    BtlCmd_CalcHPFalloffPower,
    BtlCmd_TryImprison,
    BtlCmd_TryGrudge,
    BtlCmd_TrySnatch,
    BtlCmd_CalcWeightBasedPower,
    BtlCmd_CalcWeatherBallParams,
    BtlCmd_TryPursuit,
    BtlCmd_ApplyTypeEffectiveness,
    BtlCmd_IfTurnFlag,
    BtlCmd_SetTurnFlag,
    BtlCmd_CalcGyroBallPower,
    BtlCmd_TryMetalBurst,
    BtlCmd_CalcPaybackPower,
    BtlCmd_CalcTrumpCardPower,
    BtlCmd_CalcWringOutPower,
    BtlCmd_TryMeFirst,
    BtlCmd_TryCopycat,
    BtlCmd_CalcPunishmentPower,
    BtlCmd_TrySuckerPunch,
    BtlCmd_CheckSideCondition,
    BtlCmd_TryFeint,
    BtlCmd_TryPyschoShift,
    BtlCmd_TryLastResort,
    BtlCmd_TryToxicSpikes,
    BtlCmd_CheckToxicSpikes,
    BtlCmd_CheckIgnorableAbility,
    BtlCmd_IfSameSide,
    BtlCmd_GenerateEndOfBattleItem,
    BtlCmd_TrickRoom,
    BtlCmd_IfMovedThisTurn,
    BtlCmd_CheckItemHoldEffect,
    BtlCmd_GetItemHoldEffect,
    BtlCmd_GetItemEffectParam,
    BtlCmd_TryCamouflage,
    BtlCmd_GetTerrainMove,
    BtlCmd_GetTerrainSecondaryEffect,
    BtlCmd_CalcNaturalGiftParams,
    BtlCmd_TryPluck,
    BtlCmd_TryFling,
    BtlCmd_YesNoMenu,
    BtlCmd_WaitYesNoResult,
    BtlCmd_ChoosePokemonMenu,
    BtlCmd_WaitPokemonMenuResult,
    BtlCmd_SetLinkBattleResult,
    BtlCmd_CheckStealthRock,
    BtlCmd_CheckEffectActivation,
    BtlCmd_CheckChatterActivation,
    BtlCmd_GetCurrentMoveData,
    BtlCmd_SetMosaic,
    BtlCmd_ChangeForm,
    BtlCmd_SetBattleBackground,
    BtlCmd_UseBagItem,
    BtlCmd_TryEscape,
    BtlCmd_ShowBattleStartPartyGauge,
    BtlCmd_HideBattleStartPartyGauge,
    BtlCmd_ShowPartyGauge,
    BtlCmd_HidePartyGauge,
    BtlCmd_LoadPartyGaugeGraphics,
    BtlCmd_FreePartyGaugeGraphics,
    BtlCmd_IncrementGameStat,
    BtlCmd_RestoreSprite,
    BtlCmd_TriggerAbilityOnHit,
    BtlCmd_SpriteToOAM,
    BtlCmd_OAMToSprite,
    BtlCmd_CheckWhiteout,
    BtlCmd_BoostRandomStatBy2,
    BtlCmd_RemoveItem,
    BtlCmd_TryRecycle,
    BtlCmd_CheckItemHoldEffectOnHit,
    BtlCmd_PrintBattleResultMessage,
    BtlCmd_PrintEscapeMessage,
    BtlCmd_PrintForfeitMessage,
    BtlCmd_CheckHoldOnWith1HP,
    BtlCmd_TryRestoreStatusOnSwitch,
    BtlCmd_CheckSubstitute,
    BtlCmd_CheckIgnoreWeather,
    BtlCmd_SetRandomTarget,
    BtlCmd_CheckItemHoldEffectOnUTurn,
    BtlCmd_RefreshSprite,
    BtlCmd_PlayMoveHitSound,
    BtlCmd_PlayBGM,
    BtlCmd_CheckSafariGameDone,
    BtlCmd_WaitTime,
    BtlCmd_CheckCurMoveIsType,
    BtlCmd_LoadArchivedMonData,
    BtlCmd_RefreshMonData,
    BtlCmd_222,
    BtlCmd_223,
    BtlCmd_EndScript,
};

const u8 sPickupWeightTable[9] = { 30, 40, 50, 60, 70, 80, 90, 94, 98 };

const u8 sHoneyGatherChanceTable[10] = { 5, 10, 15, 20, 25, 30, 35, 40, 45, 50 };

const u8 sCamouflageTypeTable[13] = {
    TYPE_GROUND,
    TYPE_GROUND,
    TYPE_GRASS,
    TYPE_GRASS,
    TYPE_ROCK,
    TYPE_ROCK,
    TYPE_ICE,
    TYPE_WATER,
    TYPE_ICE,
    TYPE_NORMAL,
    TYPE_GROUND,
    TYPE_FLYING,
    TYPE_NORMAL,
};
