#!/usr/bin/env bash
# PreToolUse hook (Edit|Write): block direct edits to GENERATED decomp-harness
# files. These are regenerated by scripts — hand edits are lost on the next
# regen. Exit 2 blocks the tool call; stderr is shown to Claude.

input=$(cat)
path=$(printf '%s' "$input" | python3 -c "
import json, sys
try:
    print(json.load(sys.stdin).get('tool_input', {}).get('file_path', ''))
except Exception:
    pass
" 2>/dev/null)

[ -z "$path" ] && exit 0

case "$path" in
    *tools/decomp_harness/insights.md)
        echo "BLOCKED: insights.md is GENERATED from patterns.json. Add knowledge with: python3 tools/decomp_harness/patterns.py add --json '...' (or edit patterns.json, then patterns.py gen)." >&2
        exit 2
        ;;
    *tools/decomp_harness/COVERAGE.md|*tools/decomp_harness/coverage_ledger.json)
        echo "BLOCKED: $path is GENERATED. Regenerate with: python3 tools/decomp_harness/coverage_ledger.py (edit progress.json / blockers.json instead)." >&2
        exit 2
        ;;
    *tools/decomp_harness/triage_report.json)
        echo "BLOCKED: triage_report.json is GENERATED. Regenerate with: python3 tools/decomp_harness/triage.py --rebuild." >&2
        exit 2
        ;;
    *tools/decomp_harness/knowledge.json)
        echo "BLOCKED: knowledge.json is GENERATED. Correct the per-file JSON in tools/decomp_harness/sweep/out/ and re-run: python3 tools/decomp_harness/sweep/merge_sweep.py." >&2
        exit 2
        ;;
esac

# (README.md no longer carries generated progress numbers — it links to the
# generated COVERAGE.md instead, so there is nothing to guard here.)

exit 0
