#!/usr/bin/env python3
"""Matching-knowledge pattern database.

patterns.json is the source of truth; insights.md is generated from it.

Usage:
  python3 tools/decomp_harness/patterns.py gen
      Regenerate insights.md from patterns.json.

  python3 tools/decomp_harness/patterns.py query --grep narrowing
  python3 tools/decomp_harness/patterns.py query --category ipa
  python3 tools/decomp_harness/patterns.py query --id param-copyprop-cmp
      Print matching entries (search title + body, case-insensitive).

  python3 tools/decomp_harness/patterns.py add --json '{"id":"...","category":"...","title":"...","body":"..."}'
  ... | python3 tools/decomp_harness/patterns.py add --json -
      Append a new pattern (id must be unique, category must exist) and
      regenerate insights.md.
"""

import argparse
import json
import sys
from pathlib import Path

HARNESS = Path(__file__).resolve().parent
PATTERNS = HARNESS / "patterns.json"
INSIGHTS = HARNESS / "insights.md"


def load():
    with open(PATTERNS) as f:
        return json.load(f)


def save(db):
    with open(PATTERNS, "w") as f:
        json.dump(db, f, indent=2, ensure_ascii=False)
        f.write("\n")


def cmd_gen(_args):
    db = load()
    lines = [
        "# Decomp Insights",
        "",
        "<!-- GENERATED from patterns.json by patterns.py gen — do not edit this file. -->",
        "<!-- Add knowledge with: python3 tools/decomp_harness/patterns.py add --json '...' -->",
        "",
        "Accumulated knowledge from decompilation attempts. Each insight should help",
        "future attempts match MWCC output more reliably. Query without reading the",
        "whole file: `patterns.py query --grep <word>`.",
        "",
    ]
    by_cat = {}
    for p in db["patterns"]:
        by_cat.setdefault(p["category"], []).append(p)
    for cat in db["categories"]:
        entries = by_cat.pop(cat["id"], [])
        if not entries:
            continue
        lines.append(f"## {cat['title']}")
        lines.append("")
        for p in entries:
            lines.append(f"### {p['title']}  <!-- id: {p['id']} -->")
            lines.append("")
            lines.append(p["body"])
            lines.append("")
    if by_cat:
        sys.exit(f"patterns with unknown categories: "
                 f"{[p['id'] for ps in by_cat.values() for p in ps]}")
    INSIGHTS.write_text("\n".join(lines))
    print(f"wrote {INSIGHTS} ({len(db['patterns'])} patterns)")


def cmd_query(args):
    db = load()
    needle = (args.grep or "").lower()
    hits = []
    for p in db["patterns"]:
        if args.id and p["id"] != args.id:
            continue
        if args.category and p["category"] != args.category:
            continue
        if needle and needle not in (p["id"] + " " + p["title"] + " " + p["body"]).lower():
            continue
        hits.append(p)
    if not hits:
        print("no matching patterns")
        return
    for p in hits:
        print(f"=== [{p['category']}] {p['title']} (id: {p['id']})")
        print(p["body"])
        print()
    print(f"{len(hits)} pattern(s)")


def cmd_add(args):
    raw = sys.stdin.read() if args.json == "-" else args.json
    entry = json.loads(raw)
    for field in ("id", "category", "title", "body"):
        if not entry.get(field):
            sys.exit(f"missing required field: {field}")
    db = load()
    if any(p["id"] == entry["id"] for p in db["patterns"]):
        sys.exit(f"pattern id already exists: {entry['id']} "
                 "(edit patterns.json to update it)")
    if entry["category"] not in {c["id"] for c in db["categories"]}:
        sys.exit(f"unknown category: {entry['category']} "
                 f"(one of: {', '.join(c['id'] for c in db['categories'])})")
    db["patterns"].append(entry)
    save(db)
    print(f"added pattern {entry['id']}")
    cmd_gen(args)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    gen = sub.add_parser("gen")
    gen.set_defaults(fn=cmd_gen)

    query = sub.add_parser("query")
    query.add_argument("--grep")
    query.add_argument("--category")
    query.add_argument("--id")
    query.set_defaults(fn=cmd_query)

    add = sub.add_parser("add")
    add.add_argument("--json", required=True, help="pattern entry as JSON ('-' = stdin)")
    add.set_defaults(fn=cmd_add)

    args = ap.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
